services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: django_react
    command: ../docker/wait-for-db.sh python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
